//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Earthquakes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Earthquakes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap earth_icon {
            get {
                object obj = ResourceManager.GetObject("earth_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO 3166-1 country code, FIPS 5-2 subdivision code, GNS FD, GNS UFI, ISO 639-1 language code, language script, name, latitude, longitude
        ///AF,29,PPLA,10735690,ps,arabic,&quot;شرن&quot;,33.175678,68.730449
        ///AF,29,PPLA,10735690,ps,latin,&quot;Sharan&quot;,33.175678,68.730449
        ///AF,6,PPL,-3377417,ps,latin,&quot;Pur Chaman&quot;,32.979774,63.871933
        ///AF,6,PPL,-3377417,ps,arabic,&quot;پر چمن&quot;,32.979774,63.871933
        ///AF,31,PPLA2,-3387979,ps,arabic,&quot;قرقین&quot;,37.41853,66.043581
        ///AF,31,PPLA2,-3387979,ps,latin,&quot;Qarqīn&quot;,37.41853,66.043581
        ///AF,31,PPLA2,-3383907, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string worldcities {
            get {
                return ResourceManager.GetString("worldcities", resourceCulture);
            }
        }
    }
}
